let level_1;

/**
 * Initialize the game level with chickens, small chickens, an end boss, clouds, background objects, bottles, and coins.
 */
function initLevel(){
    level_1 = new Level(
        [
            new Chicken(500), 
            new Chicken(650), 
            new Chicken(1200),
            new Chicken(2000),
            new Chicken(2300),
            new Chicken(2500),
            new Chicken(3000),
            new Chicken(3200),
            new Chicken(3400),
            new Chicken(3600),
            new Chicken(5000),
            new Chicken(5300),
            new Chicken(6000),
        ],
        [
            new SmallChicken(800),
            new SmallChicken(1500),
            new SmallChicken(1650),
            new SmallChicken(1800),
            new SmallChicken(2100),
            new SmallChicken(2700),
            new SmallChicken(3100),
            new SmallChicken(5500),
            new SmallChicken(5650),
            new SmallChicken(5800),
        ],
        [
            new Endboss()
        ],
        [
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
        ],
        [
            new BackgroundObject('./assets/img/5_background/layers/air.png', -719),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/2.png', -719),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/2.png', -719),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/2.png', -719),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 0),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/1.png', 0),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/1.png', 0),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/1.png', 0),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 719),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/2.png', 719),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/2.png', 719),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/2.png', 719),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 2),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/1.png', 719 * 2),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/1.png', 719 * 2),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/1.png', 719 * 2),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 3),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/2.png', 719 * 3),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/2.png', 719 * 3),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/2.png', 719  * 3),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 4),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/1.png', 719 * 4),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/1.png', 719 * 4),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/1.png', 719 * 4),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 5),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/2.png', 719 * 5),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/2.png', 719 * 5),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/2.png', 719 * 5),

            new BackgroundObject('./assets/img/5_background/layers/air.png', 719 * 6),
            new BackgroundObject('./assets/img/5_background/layers/3_third_layer/1.png', 719 * 6),
            new BackgroundObject('./assets/img/5_background/layers/2_second_layer/1.png', 719 * 6),
            new BackgroundObject('./assets/img/5_background/layers/1_first_layer/1.png', 719 * 6),
        ],
        [
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 200, 360),
            new Bottles('./assets/img/6_salsa_bottle/salsa_bottle.png', 500, 280),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 870, 320),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 1050, 360),
            new Bottles('./assets/img/6_salsa_bottle/salsa_bottle.png', 1250, 225),
            new Bottles('./assets/img/6_salsa_bottle/salsa_bottle.png', 1325, 230),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 1600, 320),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 1880, 360),
            new Bottles('./assets/img/6_salsa_bottle/salsa_bottle.png', 1930, 240),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 2000, 360),
            new Bottles('./assets/img/6_salsa_bottle/salsa_bottle.png', 2300, 167),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 2700, 340),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 3000, 360),
            new Bottles('./assets/img/6_salsa_bottle/salsa_bottle.png', 3360, 240),
            new Bottles('./assets/img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 3740, 300),
        ],
        [
            new Coins('./assets/img/8_coin/coin_2.png', 250, 340),
            new Coins('./assets/img/8_coin/coin_2.png', 290, 300),
            new Coins('./assets/img/8_coin/coin_2.png', 330, 260),
            new Coins('./assets/img/8_coin/coin_2.png', 370, 220),
            new Coins('./assets/img/8_coin/coin_2.png', 410, 180),
            new Coins('./assets/img/8_coin/coin_2.png', 450, 180),
            new Coins('./assets/img/8_coin/coin_2.png', 490, 220),
            new Coins('./assets/img/8_coin/coin_2.png', 530, 260),
            new Coins('./assets/img/8_coin/coin_2.png', 570, 300),
            new Coins('./assets/img/8_coin/coin_2.png', 610, 340),

            new Coins('./assets/img/8_coin/coin_1.png', 1000, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 1000, 300),
            new Coins('./assets/img/8_coin/coin_1.png', 1000, 260),
            new Coins('./assets/img/8_coin/coin_1.png', 1000, 220),
            new Coins('./assets/img/8_coin/coin_1.png', 1000, 180),
            new Coins('./assets/img/8_coin/coin_1.png', 1000, 140),
            new Coins('./assets/img/8_coin/coin_1.png', 1000, 100),

            new Coins('./assets/img/8_coin/coin_1.png', 1200, 180),
            new Coins('./assets/img/8_coin/coin_1.png', 1400, 180),
            new Coins('./assets/img/8_coin/coin_1.png', 1600, 180),
            new Coins('./assets/img/8_coin/coin_1.png', 1800, 180),
            new Coins('./assets/img/8_coin/coin_1.png', 2000, 180),
            new Coins('./assets/img/8_coin/coin_1.png', 2200, 180),
            new Coins('./assets/img/8_coin/coin_1.png', 2400, 180),

            new Coins('./assets/img/8_coin/coin_1.png', 2800, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 2850, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 2900, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 2950, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 3000, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 3050, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 3100, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 3150, 340),
            new Coins('./assets/img/8_coin/coin_1.png', 3200, 340),

            new Coins('./assets/img/8_coin/coin_1.png', 3500, 260),
            new Coins('./assets/img/8_coin/coin_1.png', 3500, 220),
        ]
    );
}